### PR TITLE
use modern Bash

### PR DESCRIPTION
**Pull request by retokromer**
- use modern shebang
- use $( . . .) instead of \`. . .\`
- use unset instead of =""
- alignment

### CODE REVIEW

**Comment by devernay** [comment]
- there's another osxDeploy.sh in Support/include which should be modified too
- why unset a variable which is used afterwards. it should be set to an empty value instead, as it is in the original version (the script should work with "bash -u"). LIBADD and alllibs should thus be set to empty values.
- bash on osx is always in /bin/bash

**Comment by retokromer** [comment]
Sorry, I was not using macOS, but implementing for Linuxes. Switching to a fork and closing this then.

**Comment by devernay** [comment]
this script is only useful on macos.
A script with a similar goal (bundling a plugin with all dependencies) could be written for linux.
However, I would recommend not using dynamic libraries for plugins. With openfx where you can make a multibundle and link all dependencies statically.

**Comment by retokromer** [comment]
Thanks for your advice, much appreciated!
We have for all the software we are using Bash installation scripts that install cross-platform for Slackware (renderfarms) and Ubuntu (workstations), as well as a little macOs and Windows Subsystem for Linux. I’ll try to do that also for the small parts of OpenFX which I would like to implement.

**Pull request closed without merging**
